from models.manager_model import ManagerModel

class ManagerController:
    def __init__(self, bot):
        self.bot = bot
        self._commands(bot)
        self.manager_model = ManagerModel()

    def _commands(self, bot):
        @bot.hybrid_command()
        async def objects(ctx, section=""): # output to discord chat the objects in Context
            if (section == "" or section == "ctx"):
                await ctx.reply(f"ctx objects: {dir(ctx)}") # using ctx.respond apparently isn't valid with update
            else:
                await ctx.reply(f"object not found")

        @bot.hybrid_command()
        async def query(ctx):
            await ctx.reply(f"guilds db query: {self.manager_model.test_query()}")

        @bot.hybrid_command()
        async def setup(ctx):
            failed = False
            
            try:
                await ctx.guild.create_text_channel("setup", reason="auto-generated by the policy bot", position=0, topic="Channel for configuring the loaded policies!")
            except Exception as e:
                await ctx.reply(f"Unable to generate setup channel: {e}")
                failed = True
            finally:
                if not failed:
                    await ctx.reply(f"Generated setup channel!")